In [1]:
import torch
import numpy as np

In [2]:
data = np.array([1, 2, 3])
type(data)

numpy.ndarray

In [3]:
torch.Tensor(data)

tensor([1., 2., 3.])

In [4]:
torch.tensor(data)

tensor([1, 2, 3], dtype=torch.int32)

In [5]:
torch.as_tensor(data)

tensor([1, 2, 3], dtype=torch.int32)

In [6]:
torch.from_numpy(data)

tensor([1, 2, 3], dtype=torch.int32)