In [3]:
import torch

In [4]:
torch.eye(7)

tensor([[1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 1.]])

In [5]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [6]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [7]:
torch.rand(2,2)

tensor([[0.1836, 0.8532],
        [0.7853, 0.4723]])