In [1]:
import torch
import numpy as np

In [2]:
t1 = torch.tensor([
    [1, 2],
    [3, 4]
], dtype = torch.float32)

t2 = torch.tensor([
    [9, 8],
    [7, 6]
], dtype = torch.float32)

In [3]:
t1[0]

tensor([1., 2.])

In [4]:
t1[0][0]

tensor(1.)

In [5]:
t2[0][0]

tensor(9.)

In [6]:
#Addiction Element Wise
t1 + t2

tensor([[10., 10.],
        [10., 10.]])

In [7]:
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

In [8]:
np.broadcast_to(2, t1.shape)

array([[2, 2],
       [2, 2]])