In [1]:
import torch

In [2]:
t = torch.tensor([
    [1, 1, 1, 1],
    [2, 2, 2, 2],
    [3, 3, 3, 3]
], dtype=torch.float32)

In [3]:
print(t.shape)
print(t.size())

torch.Size([3, 4])
torch.Size([3, 4])


In [4]:
t.shape == t.size()

True

In [5]:
rank = len(t.shape)
rank

2

In [6]:
num_of_elements = torch.tensor(t.shape).prod()
t.numel() == num_of_elements

tensor(True)

In [8]:
t.numel()


12

In [9]:
t.reshape(1, 12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [10]:
t.reshape(2, 6)

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [12]:
t.reshape(3,4)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [13]:
t.reshape(4, 3)

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])

In [15]:
t.reshape(6, 2)

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])

In [16]:
t.reshape(12, 1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

In [18]:
t.reshape(1, 1, 12)

tensor([[[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]]])

In [19]:
t.reshape(1, 2, 6)

tensor([[[1., 1., 1., 1., 2., 2.],
         [2., 2., 3., 3., 3., 3.]]])

In [20]:
t.reshape(2, 2, 3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

In [28]:
print(t.reshape(1, 12))
print(t.reshape(1, 12).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [31]:
print(t.reshape(1, 12).squeeze())
print(t.reshape(1, 12).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


In [32]:
print(t.reshape(1, 12).squeeze().unsqueeze(dim=0))
print(t.reshape(1, 12).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [39]:
t.reshape(12)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [40]:
def flatten(t):
    t = t.reshape(1, -1)
    t = t.squeeze()
    return t
def flattenOpt(t):
    t.reshape(-1)