In [8]:
import numpy as np

a = np.zeros(4)
a

array([0., 0., 0., 0.])

In [11]:
a.shape = 2, 2
a.shape

(2, 2)

In [12]:
e = np.empty(10)
e

array([7.65719726e-312, 2.37151510e-322, 0.00000000e+000, 0.00000000e+000,
       1.00238459e-044, 1.16095484e-028, 2.16209973e+233, 2.99938276e-067,
       6.48224637e+170, 3.67145870e+228])

In [14]:
np.linspace(2, 10, 5)

array([ 2.,  4.,  6.,  8., 10.])

In [15]:
np.array([10, 20])

array([10, 20])